import Foundation

/// Pure logic behind the status-item menu's "Recent Clips" section: which
/// history entries become menu items, what their titles look like, and the
/// concealed/transient pasteboard-type check the capture path uses to keep
/// secrets out of history in the first place.
///
/// Nonisolated and AppKit-free so the whole mapping is table-testable.
enum RecentClipsMenuModel {
    /// The menu shows at most this many recent entries.
    static let maxItems = 5

    /// Single-line preview length for a menu item title. Deliberately short:
    /// the menu's width follows its longest title, and a shorter preview also
    /// exposes fewer characters of anything sensitive that slipped past the
    /// concealed-type markers (not every app sets them).
    static let maxTitleLength = 30

    /// Pasteboard types that mark a copy as secret or ephemeral: the three
    /// universal identifiers plus the proprietary ones nspasteboard.org tells
    /// clipboard historians to support (1Password, TextExpander/Butler,
    /// TypeIt4Me, Typinator). Checked at CAPTURE in
    /// `ClipboardService.readClipboardContent`, so marked copies never enter
    /// `ClipboardHistory` at all — not merely hidden from this menu.
    ///
    /// The markers are cooperative: only apps that set them are excluded. A
    /// secret copied from a terminal, an editor, or a "show password" field
    /// carries no marker and enters history like any other text.
    static let sensitiveTypeIdentifiers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    /// True when any declared pasteboard type marks the copy as concealed,
    /// transient, or auto-generated.
    static func containsSensitiveType(_ typeIdentifiers: [String]) -> Bool {
        typeIdentifiers.contains(where: sensitiveTypeIdentifiers.contains)
    }

    /// Minimal input the mapping needs from a history entry. `pasteboardTypes`
    /// is empty for entries coming out of `ClipboardHistory` (sensitive copies
    /// were already dropped at capture); the field exists so the filter here is
    /// a backstop for any future call site that maps raw pasteboard reads.
    struct Clip: Equatable {
        let text: String
        let isImage: Bool
        var pasteboardTypes: [String] = []
    }

    struct Item: Equatable {
        /// Index into the input array, so the click handler can resolve the
        /// original entry without carrying it through the menu item.
        let sourceIndex: Int
        let title: String
        /// True → render the `photo` SF Symbol (NOT `doc.text.image`).
        let isImage: Bool
    }

    /// Maps history entries (most recent first) to menu-item models: drops
    /// sensitive-marked clips, truncates text to a single `maxTitleLength`
    /// line, caps at `maxItems`. Image/OCR entries title with their OCR text
    /// like any other row (the photo glyph marks the origin) — history stores
    /// only the OCR text, so that is exactly what a click re-copies, and a
    /// static label would leave several image rows indistinguishable.
    static func items(from clips: [Clip]) -> [Item] {
        var result: [Item] = []
        for (index, clip) in clips.enumerated() {
            guard !containsSensitiveType(clip.pasteboardTypes) else { continue }
            result.append(Item(sourceIndex: index, title: previewTitle(clip.text), isImage: clip.isImage))
            if result.count == maxItems { break }
        }
        return result
    }

    /// Collapses the text to one line and truncates with an ellipsis.
    /// All whitespace and control characters become plain spaces: a tab in an
    /// NSMenuItem title right-aligns the rest of the line (AppKit treats it as
    /// a key-equivalent column), and other control characters render as junk.
    private static func previewTitle(_ text: String) -> String {
        let singleLine = String(text.map { char in
            char.unicodeScalars.allSatisfy { !CharacterSet.whitespacesAndNewlines.union(.controlCharacters).contains($0) } ? char : " "
        })
        .trimmingCharacters(in: .whitespaces)
        guard singleLine.count > maxTitleLength else { return singleLine }
        return String(singleLine.prefix(maxTitleLength)) + "…"
    }
}
