import XCTest
@testable import Cai

/// (P0) Locks down the status-item menu's history → menu-item mapping. The
/// shipping bug this guards: a concealed/transient copy (a password-manager
/// secret) rendering in the menu bar for anyone looking at the screen — plus
/// the silent-bug tier (P1) of the same table: wrong truncation, raw OCR text
/// leaking where the image label belongs, or the 5-item cap not holding.
final class RecentClipsMenuModelTests: XCTestCase {

    func testHistoryToMenuItemMapping() {
        typealias Clip = RecentClipsMenuModel.Clip
        typealias Item = RecentClipsMenuModel.Item
        let long = String(repeating: "a", count: 50)
        let cases: [(name: String, clips: [Clip], expected: [Item])] = [
            (
                "concealed, transient and auto-generated copies are excluded; later entries fill the gap",
                [
                    Clip(text: "hunter2", isImage: false, pasteboardTypes: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]),
                    Clip(text: "one-time code", isImage: false, pasteboardTypes: ["org.nspasteboard.TransientType"]),
                    Clip(text: "generated pw", isImage: false, pasteboardTypes: ["org.nspasteboard.AutoGeneratedType"]),
                    Clip(text: "1p secret", isImage: false, pasteboardTypes: ["com.agilebits.onepassword"]),
                    Clip(text: "safe", isImage: false, pasteboardTypes: ["public.utf8-plain-text"]),
                ],
                [Item(sourceIndex: 4, title: "safe", isImage: false)]
            ),
            (
                "long/multi-line text (incl. tab — AppKit right-aligns after a tab in menu titles) collapses to one line, truncates at 30 chars + ellipsis",
                [Clip(text: "line one\nline\ttwo " + long, isImage: false)],
                [Item(sourceIndex: 0, title: String(("line one line two " + long).prefix(30)) + "…", isImage: false)]
            ),
            (
                "exactly 30 chars is NOT truncated (boundary)",
                [Clip(text: String(repeating: "b", count: 30), isImage: false)],
                [Item(sourceIndex: 0, title: String(repeating: "b", count: 30), isImage: false)]
            ),
            (
                "image/OCR entry keeps isImage (drives the photo glyph) and titles with its OCR preview — what a click re-copies",
                [Clip(text: "receipt total 42,50 EUR", isImage: true)],
                [Item(sourceIndex: 0, title: "receipt total 42,50 EUR", isImage: true)]
            ),
            (
                "cap holds at 5, most recent first",
                (0..<7).map { Clip(text: "clip \($0)", isImage: false) },
                (0..<5).map { Item(sourceIndex: $0, title: "clip \($0)", isImage: false) }
            ),
            (
                "fewer than 5 entries yields exactly that many, no padding",
                [Clip(text: "only", isImage: false)],
                [Item(sourceIndex: 0, title: "only", isImage: false)]
            ),
            (
                "empty history yields no items",
                [],
                []
            ),
        ]

        for testCase in cases {
            XCTAssertEqual(
                RecentClipsMenuModel.items(from: testCase.clips),
                testCase.expected,
                testCase.name
            )
        }
    }
}
